"""add_knowledge_tables

Revision ID: 0ea9fcd1a49b
Revises: cfa6b842e537
Create Date: 2026-08-28 15:26:03.661246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea9fcd1a49b'
down_revision: Union[str, None] = 'cfa6b842e537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('page_number', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_knowledge_chunks_chunk_id'), 'knowledge_chunks', ['chunk_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('effective_date', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_knowledge_sources_source_id'), 'knowledge_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_sources_source_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_knowledge_chunks_chunk_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
