"""add_assigned_officer

Revision ID: c6743cd0f9f7
Revises: 929072d5750b
Create Date: 2026-08-28 14:30:30.606679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6743cd0f9f7'
down_revision: Union[str, None] = '929072d5750b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('assigned_officer_id', sa.String(), nullable=True))
    op.create_foreign_key('cases_assigned_officer_id_fkey', 'cases', 'users', ['assigned_officer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cases_assigned_officer_id_fkey', 'cases', type_='foreignkey')
    op.drop_column('cases', 'assigned_officer_id')
    # ### end Alembic commands ###
