"""add_potential_conflicts

Revision ID: cfa6b842e537
Revises: f637dd316d93
Create Date: 2026-08-28 15:09:43.406564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa6b842e537'
down_revision: Union[str, None] = 'f637dd316d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_conflicts',
    sa.Column('conflict_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_entity_a', sa.String(), nullable=True),
    sa.Column('source_entity_b', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index(op.f('ix_potential_conflicts_conflict_id'), 'potential_conflicts', ['conflict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_potential_conflicts_conflict_id'), table_name='potential_conflicts')
    op.drop_table('potential_conflicts')
    # ### end Alembic commands ###
